Spark hdfs test
stackabletech/stackable-cluster pull request #38
Opened 2022-03-25 15:00 UTC by snocke

https://ci.stackable.tech/view/99%20Dev%20'n%20Demo/job/Functional-Cluster-tests/73/console

2022-03-28 13:58 UTC, maltesander requested changes
Tested locally and works. Just minor things.
stackable-cluster/kuttl-test/tests/spark/sparkPreparation.sh is empty and can be deleted?

From what i see there are some hardcoded (spark) versions, does it make sense to use a variable for that to use with different versions? Same goes for the custom resources of hdfs zk etc.?

2022-03-28 13:58 UTC, maltesander commented on kuttl-test/tests/.kubeassert/spark_file_exist.sh
> +      #Print success message
remove the comment?

2022-03-28 13:58 UTC, maltesander commented on kuttl-test/tests/.kubeassert/spark_hdfs_file_exist.sh
> +    # export NAME_NODE_POD=$(kubectl -n ${NAMESPACE} get pods -o=name | grep hdfs-namenode-default-0 | sed "s/^.\{4\}//")
The TODO still relevant?

2022-03-28 13:58 UTC, maltesander commented on kuttl-test/tests/.kubeassert/spark_hdfs_file_exist.sh
> +    kubectl exec -n $NAMESPACE $NAME_NODE_POD -- /bin/bash -c "unset HADOOP_OPTS && bin/hdfs dfs -test -e /tmp/$1"
You can remove the `unset`. https://github.com/stackabletech/hdfs-operator/pull/148 is merged and should be available in the dev helm repo (it is not tagged and in the stable repo yet)

2022-03-28 13:58 UTC, maltesander commented on kuttl-test/tests/spark/sparkHdfs/sparkPreparation.sh
> +#kubectl -n ${NAMESPACE} cp ${RESOURCE_FILE} $SPARK_SLAVE_POD:/tmp
remove?

2022-03-28 13:58 UTC, maltesander commented on kuttl-test/tests/spark/sparkHdfs/sparkPreparation.sh
> +kubectl exec -n ${NAMESPACE} hdfs-namenode-default-0 -- /bin/bash -x -v -c "unset HADOOP_OPTS"
It is merged and available in helm/dev

2022-03-28 13:58 UTC, maltesander commented on kuttl-test/tests/.kubeassert/spark_hdfs_file_exist.sh
>      fi
I dont like these comments. It is obvious what happens, you can remove them.
Furthermore i would simplify the logging:

    # Validate results
    if [ $? -eq 0 ]; then
        logger::info "$1 exists on $NAME_NODE_POD"
    else
        logger::fail "$1 missing on $NAME_NODE_POD"
    fi

2022-03-28 14:55 UTC, snocke commented on kuttl-test/tests/.kubeassert/spark_hdfs_file_exist.sh
> +    # export NAME_NODE_POD=$(kubectl -n ${NAMESPACE} get pods -o=name | grep hdfs-namenode-default-0 | sed "s/^.\{4\}//")
Yes. Haven't looked into a better way just yet. Let me know if you have any spontaneous ideas.

2022-03-28 14:55 UTC, snocke commented on kuttl-test/tests/.kubeassert/spark_hdfs_file_exist.sh
> +    kubectl exec -n $NAMESPACE $NAME_NODE_POD -- /bin/bash -c "unset HADOOP_OPTS && bin/hdfs dfs -test -e /tmp/$1"
done

2022-03-28 14:56 UTC, snocke commented on kuttl-test/tests/spark/sparkHdfs/sparkPreparation.sh
> +#kubectl -n ${NAMESPACE} cp ${RESOURCE_FILE} $SPARK_SLAVE_POD:/tmp
yes. done

2022-03-28 14:56 UTC, snocke commented on kuttl-test/tests/spark/sparkHdfs/sparkPreparation.sh
> +kubectl exec -n ${NAMESPACE} hdfs-namenode-default-0 -- /bin/bash -x -v -c "unset HADOOP_OPTS"
nice. removal done.

2022-03-28 14:57 UTC, snocke commented on kuttl-test/tests/.kubeassert/spark_hdfs_file_exist.sh
>      fi
Ok. Agree. Applied your suggestion

2022-03-29 08:01 UTC, maltesander approved these changes
LGTM.

2022-04-11 12:39 UTC, closed without merging

2022-04-11 12:40 UTC, snocke commented
Done in Convert to maven pom#42