Edit t2 user
stackabletech/stackable-cluster pull request #45
Opened 2022-04-12 13:16 UTC by snocke

2022-04-13 13:53 UTC, backstreetkiwi commented
The test run in Jenkins (https://ci.stackable.tech/view/99%20Dev%20'n%20Demo/job/Functional-Cluster-tests/88/) produced two `target/` folders in the two Maven projects which were owned by `root`. Are you sure that setting the Docker `label` will do the trick in this case? Have you tried `--user` (`-u`) ?

2022-04-13 13:54 UTC, backstreetkiwi requested changes
See other comment

2022-04-19 10:31 UTC, snocke commented
Thanks @backstreetkiwi for your answer. I've refactored it to `docker run -u $(id -u ${USER}):$(id -g ${USER})` which resolves to `docker run -u 1000:1000`. https://ci.stackable.tech/view/99%20Dev%20'n%20Demo/job/Functional-Cluster-tests/89/consoleFull Is this doing the trick?

2022-04-20 07:37 UTC, backstreetkiwi approved these changes

2022-04-25 06:14 UTC, merged